using ch.appl.psoft.Common;
using ch.appl.psoft.db;
using System;
using Telerik.Web.UI;

namespace ch.appl.psoft.Payment
{
    public partial class Order : PsoftMainPage
    {
        public String ConnectionString;
        protected void Page_Load(object sender, EventArgs e)
        {
            this.BreadcrumbCaption = _mapper.get("ModuleNames", "payment");
            this.BreadcrumbLink = Global.Config.baseURL + "/Payment/Order.aspx";
            //if (!Page.IsPostBack)
            //{
            DBData db = DBData.getDBData(Session);
            db.connect();
            string connetionString = ((System.Data.SqlClient.SqlConnection)db.connection).ConnectionString;
            connetionString += ";Password=" + Global.Config.dbPassword;
            ConnectionString = connetionString;
            SqlDataSource.ConnectionString = connetionString;
            SqlDataSource1.ConnectionString = connetionString;
            //ProductTable.Culture = CultureInfo.CreateSpecificCulture("de-DE");
            if (db.hasRowAuthorisation(DBData.AUTHORISATION.ADMIN, "PERSON", db.userId, true, true))
            {
                ProductTable.AllowAutomaticDeletes = true;
                ProductTable.AllowAutomaticInserts = true;
                ProductTable.AllowAutomaticUpdates = true;
                ProductTable.AutoGenerateDeleteColumn = true;
                ProductTable.AllowAutomaticInserts = true;
                ProductTable.AutoGenerateEditColumn = true;
                ProductTable.MasterTableView.CommandItemDisplay = GridCommandItemDisplay.Bottom;
                GridButtonColumn Order = (GridButtonColumn)ProductTable.MasterTableView.Columns.FindByUniqueName("PayButton");
                Order.Visible = false;

            }
            else
            {
                ProductTable.AllowAutomaticDeletes = false;
                ProductTable.AllowAutomaticInserts = false;
                ProductTable.AllowAutomaticUpdates = false;
                ProductTable.AutoGenerateDeleteColumn = false;
                ProductTable.AllowAutomaticInserts = false;
                ProductTable.AutoGenerateEditColumn = false;
                ProductTable.MasterTableView.CommandItemDisplay = GridCommandItemDisplay.None;
                GridButtonColumn Order = (GridButtonColumn)ProductTable.MasterTableView.Columns.FindByUniqueName("PayButton");
                Order.ImageUrl = Global.Config.baseURL + "/IMAGES/kaufen_button.png";

                int numOfCards = (int)db.lookup("NUMBER_OF_CARDS", "PERSON", "ID=" + db.userId);
                if (numOfCards < 1) numOfCards = 0;
                lblNumCards.Text = "Sie haben noch " + numOfCards + " Karten zur Verfügung.";
            }
           
            
            ProductTable.Skin = "MetroTouch";
            ProductTable.RenderMode = RenderMode.Lightweight;
            db.disconnect();

            //}
        }

        protected void ProductTable_ItemCommand(object sender, GridCommandEventArgs e)
        {
            if (e.CommandName == "pay")
            {
                GridDataItem item = (GridDataItem)e.Item;
                Session.Add("OrderItem", item.GetDataKeyValue("ID").ToString());
                Response.Redirect("Pay.aspx");
            }
        }
    }
}