//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadPivotGrid {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadPivotGrid.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggregate fields ähnelt.
        /// </summary>
        internal static string AggregateGroupedFieldsTitle {
            get {
                return ResourceManager.GetString("AggregateGroupedFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Begins With... ähnelt.
        /// </summary>
        internal static string BeginsWithText {
            get {
                return ResourceManager.GetString("BeginsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom ähnelt.
        /// </summary>
        internal static string BottomText {
            get {
                return ResourceManager.GetString("BottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Page Size ähnelt.
        /// </summary>
        internal static string ChangePageSizeButtonToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ChangePageSizeComboBoxTableSummary {
            get {
                return ResourceManager.GetString("ChangePageSizeComboBoxTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ChangePageSizeComboBoxToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page size: ähnelt.
        /// </summary>
        internal static string ChangePageSizeLabelText {
            get {
                return ResourceManager.GetString("ChangePageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        internal static string ChangePageSizeLinkButtonText {
            get {
                return ResourceManager.GetString("ChangePageSizeLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ChangePageSizeTextBoxToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Filter From ähnelt.
        /// </summary>
        internal static string ClearFilterFromText {
            get {
                return ResourceManager.GetString("ClearFilterFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Filters ähnelt.
        /// </summary>
        internal static string ClearFiltersText {
            get {
                return ResourceManager.GetString("ClearFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collapse ähnelt.
        /// </summary>
        internal static string CollapseButtonToolTip {
            get {
                return ResourceManager.GetString("CollapseButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column fields ähnelt.
        /// </summary>
        internal static string ColumnGroupedFieldsTitle {
            get {
                return ResourceManager.GetString("ColumnGroupedFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ColumnHeaderTableCaption {
            get {
                return ResourceManager.GetString("ColumnHeaderTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ColumnHeaderTableSummary {
            get {
                return ResourceManager.GetString("ColumnHeaderTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drop Column Fields Here ähnelt.
        /// </summary>
        internal static string ColumnHeaderZoneText {
            get {
                return ResourceManager.GetString("ColumnHeaderZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width: &lt;strong&gt;{0}&lt;/strong&gt; &lt;em&gt;pixels&lt;/em&gt; ähnelt.
        /// </summary>
        internal static string ColumnResizeTooltipFormatString {
            get {
                return ResourceManager.GetString("ColumnResizeTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aggregate Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelAggregateFieldsText {
            get {
                return ResourceManager.GetString("ConfigurationPanelAggregateFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelAllFieldsText {
            get {
                return ResourceManager.GetString("ConfigurationPanelAllFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Layout ähnelt.
        /// </summary>
        internal static string ConfigurationPanelChangeLayoutButtonText {
            get {
                return ResourceManager.GetString("ConfigurationPanelChangeLayoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelColumnFieldsText {
            get {
                return ResourceManager.GetString("ConfigurationPanelColumnFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Field ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuHideField {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuHideField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Down ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveDown {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to Aggregate Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveToAggregateFields {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveToAggregateFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to Beginning ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveToBeginning {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to Column Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveToColumnFields {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveToColumnFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to End ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveToEnd {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to Filter Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveToFilterFields {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveToFilterFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move to Row Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveToRowFields {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveToRowFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move Up ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuMoveUp {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One-By-Four ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuOneByFour {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuOneByFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Side-By-Side ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuSideBySide {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuSideBySide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stacked ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuStacked {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuStacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summarize By Settings ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuSummarizeBySettings {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuSummarizeBySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Two-By-Two ähnelt.
        /// </summary>
        internal static string ConfigurationPanelContextMenuTwoByTwo {
            get {
                return ResourceManager.GetString("ConfigurationPanelContextMenuTwoByTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Defer Layout Update ähnelt.
        /// </summary>
        internal static string ConfigurationPanelDeferLayoutUpdateCheckBoxText {
            get {
                return ResourceManager.GetString("ConfigurationPanelDeferLayoutUpdateCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelFilterFieldsText {
            get {
                return ResourceManager.GetString("ConfigurationPanelFilterFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Row Fields ähnelt.
        /// </summary>
        internal static string ConfigurationPanelRowFieldsText {
            get {
                return ResourceManager.GetString("ConfigurationPanelRowFieldsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string ConfigurationPanelUpdateButtonText {
            get {
                return ResourceManager.GetString("ConfigurationPanelUpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contains... ähnelt.
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drop Data Fields Here ähnelt.
        /// </summary>
        internal static string DataHeaderZoneText {
            get {
                return ResourceManager.GetString("DataHeaderZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DataTableCaption {
            get {
                return ResourceManager.GetString("DataTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string DataTableSummary {
            get {
                return ResourceManager.GetString("DataTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Does Not Begin With... ähnelt.
        /// </summary>
        internal static string DoesNotBeginWithText {
            get {
                return ResourceManager.GetString("DoesNotBeginWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Does Not Contain... ähnelt.
        /// </summary>
        internal static string DoesNotContainText {
            get {
                return ResourceManager.GetString("DoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Does Not End With... ähnelt.
        /// </summary>
        internal static string DoesNotEndWithText {
            get {
                return ResourceManager.GetString("DoesNotEndWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Does Not Equal... ähnelt.
        /// </summary>
        internal static string DoesNotEqualText {
            get {
                return ResourceManager.GetString("DoesNotEqualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag to reorder ähnelt.
        /// </summary>
        internal static string DragToReorder {
            get {
                return ResourceManager.GetString("DragToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag to resize ähnelt.
        /// </summary>
        internal static string DragToResize {
            get {
                return ResourceManager.GetString("DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ends With... ähnelt.
        /// </summary>
        internal static string EndsWithText {
            get {
                return ResourceManager.GetString("EndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Equals... ähnelt.
        /// </summary>
        internal static string EqualsText {
            get {
                return ResourceManager.GetString("EqualsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string ErrorValueText {
            get {
                return ResourceManager.GetString("ErrorValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excludes ähnelt.
        /// </summary>
        internal static string ExcludesText {
            get {
                return ResourceManager.GetString("ExcludesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expand ähnelt.
        /// </summary>
        internal static string ExpandButtonToolTip {
            get {
                return ResourceManager.GetString("ExpandButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string FieldSettingsWindowCancelButton {
            get {
                return ResourceManager.GetString("FieldSettingsWindowCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string FieldSettingsWindowOKButton {
            get {
                return ResourceManager.GetString("FieldSettingsWindowOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RadPivotGrid Fields Window ähnelt.
        /// </summary>
        internal static string FieldsWindowTitle {
            get {
                return ResourceManager.GetString("FieldsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        internal static string FilterDialogAndLabelText {
            get {
                return ResourceManager.GetString("FilterDialogAndLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by ähnelt.
        /// </summary>
        internal static string FilterDialogByLabelText {
            get {
                return ResourceManager.GetString("FilterDialogByLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string FilterDialogCancelButtonText {
            get {
                return ResourceManager.GetString("FilterDialogCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string FilterDialogOKButtonText {
            get {
                return ResourceManager.GetString("FilterDialogOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter fields ähnelt.
        /// </summary>
        internal static string FilterGroupedFieldsTitle {
            get {
                return ResourceManager.GetString("FilterGroupedFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drop Filter Fields Here ähnelt.
        /// </summary>
        internal static string FilterHeaderZoneText {
            get {
                return ResourceManager.GetString("FilterHeaderZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore case ähnelt.
        /// </summary>
        internal static string FiltersWindowIgnoreCaseCheckBoxText {
            get {
                return ResourceManager.GetString("FiltersWindowIgnoreCaseCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string FiltersWindowOKButtonText {
            get {
                return ResourceManager.GetString("FiltersWindowOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string FilterWindowCancelButtonText {
            get {
                return ResourceManager.GetString("FilterWindowCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter Window ähnelt.
        /// </summary>
        internal static string FilterWindowText {
            get {
                return ResourceManager.GetString("FilterWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die First Page ähnelt.
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to Page ähnelt.
        /// </summary>
        internal static string GoToPageButtonToolTip {
            get {
                return ResourceManager.GetString("GoToPageButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page: ähnelt.
        /// </summary>
        internal static string GoToPageLabelText {
            get {
                return ResourceManager.GetString("GoToPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go ähnelt.
        /// </summary>
        internal static string GoToPageLinkButtonText {
            get {
                return ResourceManager.GetString("GoToPageLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string GoToPageTextBoxToolTip {
            get {
                return ResourceManager.GetString("GoToPageTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grand Total ähnelt.
        /// </summary>
        internal static string GrandTotalText {
            get {
                return ResourceManager.GetString("GrandTotalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Includes ähnelt.
        /// </summary>
        internal static string IncludesText {
            get {
                return ResourceManager.GetString("IncludesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Between... ähnelt.
        /// </summary>
        internal static string IsBetweenText {
            get {
                return ResourceManager.GetString("IsBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greater Than Or Equal To... ähnelt.
        /// </summary>
        internal static string IsGreaterThanOrEqualToText {
            get {
                return ResourceManager.GetString("IsGreaterThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Greater Than... ähnelt.
        /// </summary>
        internal static string IsGreaterThanText {
            get {
                return ResourceManager.GetString("IsGreaterThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Less Than Or Equal To... ähnelt.
        /// </summary>
        internal static string IsLessThanOrEqualToText {
            get {
                return ResourceManager.GetString("IsLessThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Less Than... ähnelt.
        /// </summary>
        internal static string IsLessThanText {
            get {
                return ResourceManager.GetString("IsLessThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not Between... ähnelt.
        /// </summary>
        internal static string IsNotBetweenText {
            get {
                return ResourceManager.GetString("IsNotBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Items ähnelt.
        /// </summary>
        internal static string ItemsText {
            get {
                return ResourceManager.GetString("ItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label Filters ähnelt.
        /// </summary>
        internal static string LabelFiltersText {
            get {
                return ResourceManager.GetString("LabelFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label filter ähnelt.
        /// </summary>
        internal static string LabelFilterText {
            get {
                return ResourceManager.GetString("LabelFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Page ähnelt.
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Page ähnelt.
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No records to display. ähnelt.
        /// </summary>
        internal static string NoRecordsText {
            get {
                return ResourceManager.GetString("NoRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open filter window ähnelt.
        /// </summary>
        internal static string OpenFilterWindowTooltip {
            get {
                return ResourceManager.GetString("OpenFilterWindowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string OuterTableCaption {
            get {
                return ResourceManager.GetString("OuterTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string OuterTableSummary {
            get {
                return ResourceManager.GetString("OuterTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of {0} ähnelt.
        /// </summary>
        internal static string PageOfLabelText {
            get {
                return ResourceManager.GetString("PageOfLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease ähnelt.
        /// </summary>
        internal static string PageSliderDecreaseToolTip {
            get {
                return ResourceManager.GetString("PageSliderDecreaseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag ähnelt.
        /// </summary>
        internal static string PageSliderDragToolTip {
            get {
                return ResourceManager.GetString("PageSliderDragToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase ähnelt.
        /// </summary>
        internal static string PageSliderIncreaseToolTip {
            get {
                return ResourceManager.GetString("PageSliderIncreaseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt; ähnelt.
        /// </summary>
        internal static string PageSliderPagerLabel {
            get {
                return ResourceManager.GetString("PageSliderPagerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percent ähnelt.
        /// </summary>
        internal static string PercentText {
            get {
                return ResourceManager.GetString("PercentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous Page ähnelt.
        /// </summary>
        internal static string PrevPageToolTip {
            get {
                return ResourceManager.GetString("PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please do not remove this key. ähnelt.
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Row fields ähnelt.
        /// </summary>
        internal static string RowGroupedFieldsTitle {
            get {
                return ResourceManager.GetString("RowGroupedFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string RowHeaderTableCaption {
            get {
                return ResourceManager.GetString("RowHeaderTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string RowHeaderTableSummary {
            get {
                return ResourceManager.GetString("RowHeaderTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drop Row Fields Here ähnelt.
        /// </summary>
        internal static string RowHeaderZoneText {
            get {
                return ResourceManager.GetString("RowHeaderZoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (Select All) ähnelt.
        /// </summary>
        internal static string SelectAllText {
            get {
                return ResourceManager.GetString("SelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string ShowHideCheckBoxToolTip {
            get {
                return ResourceManager.GetString("ShowHideCheckBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort descending ähnelt.
        /// </summary>
        internal static string SortIconAscText {
            get {
                return ResourceManager.GetString("SortIconAscText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorted asc ähnelt.
        /// </summary>
        internal static string SortIconAscTooltip {
            get {
                return ResourceManager.GetString("SortIconAscTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ascending ähnelt.
        /// </summary>
        internal static string SortIconDescText {
            get {
                return ResourceManager.GetString("SortIconDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorted desc ähnelt.
        /// </summary>
        internal static string SortIconDescTooltip {
            get {
                return ResourceManager.GetString("SortIconDescTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summarize By Settings ähnelt.
        /// </summary>
        internal static string SummarizeBySettingsTitle {
            get {
                return ResourceManager.GetString("SummarizeBySettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column:  ähnelt.
        /// </summary>
        internal static string ToolTipsColumnText {
            get {
                return ResourceManager.GetString("ToolTipsColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Row:  ähnelt.
        /// </summary>
        internal static string ToolTipsRowText {
            get {
                return ResourceManager.GetString("ToolTipsRowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value:  ähnelt.
        /// </summary>
        internal static string ToolTipsValueText {
            get {
                return ResourceManager.GetString("ToolTipsValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top... ähnelt.
        /// </summary>
        internal static string TopText {
            get {
                return ResourceManager.GetString("TopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total {0} ähnelt.
        /// </summary>
        internal static string TotalValueFormat {
            get {
                return ResourceManager.GetString("TotalValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value Filters ähnelt.
        /// </summary>
        internal static string ValueFiltersText {
            get {
                return ResourceManager.GetString("ValueFiltersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value filter ähnelt.
        /// </summary>
        internal static string ValueFilterText {
            get {
                return ResourceManager.GetString("ValueFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Total ähnelt.
        /// </summary>
        internal static string ValueTotalFormat {
            get {
                return ResourceManager.GetString("ValueTotalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string WrapperTableCaption {
            get {
                return ResourceManager.GetString("WrapperTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string WrapperTableSummary {
            get {
                return ResourceManager.GetString("WrapperTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide ähnelt.
        /// </summary>
        internal static string ZoneContextMenuHide {
            get {
                return ResourceManager.GetString("ZoneContextMenuHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Fields Window ähnelt.
        /// </summary>
        internal static string ZoneContextMenuHideFieldsWindow {
            get {
                return ResourceManager.GetString("ZoneContextMenuHideFieldsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        internal static string ZoneContextMenuRefresh {
            get {
                return ResourceManager.GetString("ZoneContextMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Fields Window ähnelt.
        /// </summary>
        internal static string ZoneContextMenuShowFieldsWindow {
            get {
                return ResourceManager.GetString("ZoneContextMenuShowFieldsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summarize By Settings ähnelt.
        /// </summary>
        internal static string ZoneContextMenuSummarizeBySettings {
            get {
                return ResourceManager.GetString("ZoneContextMenuSummarizeBySettings", resourceCulture);
            }
        }
    }
}
