//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadScheduler {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadScheduler.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After ähnelt.
        /// </summary>
        internal static string AdvancedAfter {
            get {
                return ResourceManager.GetString("AdvancedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All day ähnelt.
        /// </summary>
        internal static string AdvancedAllDayEvent {
            get {
                return ResourceManager.GetString("AdvancedAllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string AdvancedCalendarCancel {
            get {
                return ResourceManager.GetString("AdvancedCalendarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string AdvancedCalendarOK {
            get {
                return ResourceManager.GetString("AdvancedCalendarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today ähnelt.
        /// </summary>
        internal static string AdvancedCalendarToday {
            get {
                return ResourceManager.GetString("AdvancedCalendarToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        internal static string AdvancedClose {
            get {
                return ResourceManager.GetString("AdvancedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daily ähnelt.
        /// </summary>
        internal static string AdvancedDaily {
            get {
                return ResourceManager.GetString("AdvancedDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string AdvancedDay {
            get {
                return ResourceManager.GetString("AdvancedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day of the month ähnelt.
        /// </summary>
        internal static string AdvancedDayOfMonth {
            get {
                return ResourceManager.GetString("AdvancedDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day of the week ähnelt.
        /// </summary>
        internal static string AdvancedDayOfWeek {
            get {
                return ResourceManager.GetString("AdvancedDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day(s) ähnelt.
        /// </summary>
        internal static string AdvancedDays {
            get {
                return ResourceManager.GetString("AdvancedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string AdvancedDescription {
            get {
                return ResourceManager.GetString("AdvancedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Done ähnelt.
        /// </summary>
        internal static string AdvancedDone {
            get {
                return ResourceManager.GetString("AdvancedDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Appointment ähnelt.
        /// </summary>
        internal static string AdvancedEditAppointment {
            get {
                return ResourceManager.GetString("AdvancedEditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End after ähnelt.
        /// </summary>
        internal static string AdvancedEndAfter {
            get {
                return ResourceManager.GetString("AdvancedEndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End by ähnelt.
        /// </summary>
        internal static string AdvancedEndByThisDate {
            get {
                return ResourceManager.GetString("AdvancedEndByThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End date is required ähnelt.
        /// </summary>
        internal static string AdvancedEndDateRequired {
            get {
                return ResourceManager.GetString("AdvancedEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End time is required ähnelt.
        /// </summary>
        internal static string AdvancedEndTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedEndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every ähnelt.
        /// </summary>
        internal static string AdvancedEvery {
            get {
                return ResourceManager.GetString("AdvancedEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every weekday ähnelt.
        /// </summary>
        internal static string AdvancedEveryWeekday {
            get {
                return ResourceManager.GetString("AdvancedEveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Every working day ähnelt.
        /// </summary>
        internal static string AdvancedEveryWorkingDay {
            get {
                return ResourceManager.GetString("AdvancedEveryWorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die first ähnelt.
        /// </summary>
        internal static string AdvancedFirst {
            get {
                return ResourceManager.GetString("AdvancedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die fourth ähnelt.
        /// </summary>
        internal static string AdvancedFourth {
            get {
                return ResourceManager.GetString("AdvancedFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start time ähnelt.
        /// </summary>
        internal static string AdvancedFrom {
            get {
                return ResourceManager.GetString("AdvancedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hourly ähnelt.
        /// </summary>
        internal static string AdvancedHourly {
            get {
                return ResourceManager.GetString("AdvancedHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour(s) ähnelt.
        /// </summary>
        internal static string AdvancedHours {
            get {
                return ResourceManager.GetString("AdvancedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid number ähnelt.
        /// </summary>
        internal static string AdvancedInvalidNumber {
            get {
                return ResourceManager.GetString("AdvancedInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die last ähnelt.
        /// </summary>
        internal static string AdvancedLast {
            get {
                return ResourceManager.GetString("AdvancedLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day ähnelt.
        /// </summary>
        internal static string AdvancedMaskDay {
            get {
                return ResourceManager.GetString("AdvancedMaskDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weekday ähnelt.
        /// </summary>
        internal static string AdvancedMaskWeekday {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weekend day ähnelt.
        /// </summary>
        internal static string AdvancedMaskWeekendDay {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monthly ähnelt.
        /// </summary>
        internal static string AdvancedMonthly {
            get {
                return ResourceManager.GetString("AdvancedMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die month(s) ähnelt.
        /// </summary>
        internal static string AdvancedMonths {
            get {
                return ResourceManager.GetString("AdvancedMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More details ähnelt.
        /// </summary>
        internal static string AdvancedMoreDetails {
            get {
                return ResourceManager.GetString("AdvancedMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Never ähnelt.
        /// </summary>
        internal static string AdvancedNever {
            get {
                return ResourceManager.GetString("AdvancedNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Appointment ähnelt.
        /// </summary>
        internal static string AdvancedNewAppointment {
            get {
                return ResourceManager.GetString("AdvancedNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No end date ähnelt.
        /// </summary>
        internal static string AdvancedNoEndDate {
            get {
                return ResourceManager.GetString("AdvancedNoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die occurrences ähnelt.
        /// </summary>
        internal static string AdvancedOccurrences {
            get {
                return ResourceManager.GetString("AdvancedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of ähnelt.
        /// </summary>
        internal static string AdvancedOf {
            get {
                return ResourceManager.GetString("AdvancedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die of every ähnelt.
        /// </summary>
        internal static string AdvancedOfEvery {
            get {
                return ResourceManager.GetString("AdvancedOfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        internal static string AdvancedOn {
            get {
                return ResourceManager.GetString("AdvancedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range of recurrence: ähnelt.
        /// </summary>
        internal static string AdvancedRange {
            get {
                return ResourceManager.GetString("AdvancedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recur every ähnelt.
        /// </summary>
        internal static string AdvancedRecurEvery {
            get {
                return ResourceManager.GetString("AdvancedRecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recurrence ähnelt.
        /// </summary>
        internal static string AdvancedRecurrence {
            get {
                return ResourceManager.GetString("AdvancedRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recurring task ähnelt.
        /// </summary>
        internal static string AdvancedRecurringAppointment {
            get {
                return ResourceManager.GetString("AdvancedRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat ähnelt.
        /// </summary>
        internal static string AdvancedRepeat {
            get {
                return ResourceManager.GetString("AdvancedRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat Appointment ähnelt.
        /// </summary>
        internal static string AdvancedRepeatAppointment {
            get {
                return ResourceManager.GetString("AdvancedRepeatAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat End ähnelt.
        /// </summary>
        internal static string AdvancedRepeatEnd {
            get {
                return ResourceManager.GetString("AdvancedRepeatEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat On ähnelt.
        /// </summary>
        internal static string AdvancedRepeatOn {
            get {
                return ResourceManager.GetString("AdvancedRepeatOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reset exceptions ähnelt.
        /// </summary>
        internal static string AdvancedReset {
            get {
                return ResourceManager.GetString("AdvancedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die second ähnelt.
        /// </summary>
        internal static string AdvancedSecond {
            get {
                return ResourceManager.GetString("AdvancedSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start date is required ähnelt.
        /// </summary>
        internal static string AdvancedStartDateRequired {
            get {
                return ResourceManager.GetString("AdvancedStartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start time must be before end time ähnelt.
        /// </summary>
        internal static string AdvancedStartTimeBeforeEndTime {
            get {
                return ResourceManager.GetString("AdvancedStartTimeBeforeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start time is required ähnelt.
        /// </summary>
        internal static string AdvancedStartTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject ähnelt.
        /// </summary>
        internal static string AdvancedSubject {
            get {
                return ResourceManager.GetString("AdvancedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide appointment subject ähnelt.
        /// </summary>
        internal static string AdvancedSubjectRequired {
            get {
                return ResourceManager.GetString("AdvancedSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The ähnelt.
        /// </summary>
        internal static string AdvancedThe {
            get {
                return ResourceManager.GetString("AdvancedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die third ähnelt.
        /// </summary>
        internal static string AdvancedThird {
            get {
                return ResourceManager.GetString("AdvancedThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time zone ähnelt.
        /// </summary>
        internal static string AdvancedTimeZone {
            get {
                return ResourceManager.GetString("AdvancedTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End time ähnelt.
        /// </summary>
        internal static string AdvancedTo {
            get {
                return ResourceManager.GetString("AdvancedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weekly ähnelt.
        /// </summary>
        internal static string AdvancedWeekly {
            get {
                return ResourceManager.GetString("AdvancedWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die week(s) on ähnelt.
        /// </summary>
        internal static string AdvancedWeeks {
            get {
                return ResourceManager.GetString("AdvancedWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Working... ähnelt.
        /// </summary>
        internal static string AdvancedWorking {
            get {
                return ResourceManager.GetString("AdvancedWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yearly ähnelt.
        /// </summary>
        internal static string AdvancedYearly {
            get {
                return ResourceManager.GetString("AdvancedYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die year(s) ähnelt.
        /// </summary>
        internal static string AdvancedYears {
            get {
                return ResourceManager.GetString("AdvancedYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die all day ähnelt.
        /// </summary>
        internal static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete this appointment? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm delete ähnelt.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string ConfirmOK {
            get {
                return ResourceManager.GetString("ConfirmOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete only this occurrence. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceDeleteOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete the series. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceDeleteSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting a recurring appointment ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit only this occurrence. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceEditOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit the series. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceEditSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editing a recurring appointment ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceEditTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move only this occurrence. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceMoveOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move the series. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceMoveSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moving a recurring appointment ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceMoveTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resize only this occurrence. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceResizeOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resize the series. ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceResizeSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resizing a recurring appointment ähnelt.
        /// </summary>
        internal static string ConfirmRecurrenceResizeTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete all existing recurrence exceptions? ähnelt.
        /// </summary>
        internal static string ConfirmResetExceptionsText {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm reset exceptions ähnelt.
        /// </summary>
        internal static string ConfirmResetExceptionsTitle {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Appointment ähnelt.
        /// </summary>
        internal static string ContextMenuAddAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Recurring Appointment ähnelt.
        /// </summary>
        internal static string ContextMenuAddRecurringAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go to today ähnelt.
        /// </summary>
        internal static string ContextMenuGoToToday {
            get {
                return ResourceManager.GetString("ContextMenuGoToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day ähnelt.
        /// </summary>
        internal static string HeaderDay {
            get {
                return ResourceManager.GetString("HeaderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Month ähnelt.
        /// </summary>
        internal static string HeaderMonth {
            get {
                return ResourceManager.GetString("HeaderMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multi-day ähnelt.
        /// </summary>
        internal static string HeaderMultiDay {
            get {
                return ResourceManager.GetString("HeaderMultiDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die next day ähnelt.
        /// </summary>
        internal static string HeaderNextDay {
            get {
                return ResourceManager.GetString("HeaderNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die previous day ähnelt.
        /// </summary>
        internal static string HeaderPrevDay {
            get {
                return ResourceManager.GetString("HeaderPrevDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timeline ähnelt.
        /// </summary>
        internal static string HeaderTimeline {
            get {
                return ResourceManager.GetString("HeaderTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die today ähnelt.
        /// </summary>
        internal static string HeaderToday {
            get {
                return ResourceManager.GetString("HeaderToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Week ähnelt.
        /// </summary>
        internal static string HeaderWeek {
            get {
                return ResourceManager.GetString("HeaderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminder ähnelt.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die before start ähnelt.
        /// </summary>
        internal static string ReminderBeforeStart {
            get {
                return ResourceManager.GetString("ReminderBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die day ähnelt.
        /// </summary>
        internal static string ReminderDay {
            get {
                return ResourceManager.GetString("ReminderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die days ähnelt.
        /// </summary>
        internal static string ReminderDays {
            get {
                return ResourceManager.GetString("ReminderDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dismiss ähnelt.
        /// </summary>
        internal static string ReminderDismiss {
            get {
                return ResourceManager.GetString("ReminderDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dismiss All ähnelt.
        /// </summary>
        internal static string ReminderDismissAll {
            get {
                return ResourceManager.GetString("ReminderDismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die due in ähnelt.
        /// </summary>
        internal static string ReminderDueIn {
            get {
                return ResourceManager.GetString("ReminderDueIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hour ähnelt.
        /// </summary>
        internal static string ReminderHour {
            get {
                return ResourceManager.GetString("ReminderHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hours ähnelt.
        /// </summary>
        internal static string ReminderHours {
            get {
                return ResourceManager.GetString("ReminderHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minute ähnelt.
        /// </summary>
        internal static string ReminderMinute {
            get {
                return ResourceManager.GetString("ReminderMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die minutes ähnelt.
        /// </summary>
        internal static string ReminderMinutes {
            get {
                return ResourceManager.GetString("ReminderMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string ReminderNone {
            get {
                return ResourceManager.GetString("ReminderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Item ähnelt.
        /// </summary>
        internal static string ReminderOpenItem {
            get {
                return ResourceManager.GetString("ReminderOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overdue ähnelt.
        /// </summary>
        internal static string ReminderOverdue {
            get {
                return ResourceManager.GetString("ReminderOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reminders ähnelt.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Snooze ähnelt.
        /// </summary>
        internal static string ReminderSnooze {
            get {
                return ResourceManager.GetString("ReminderSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click Snooze to be reminded again in: ähnelt.
        /// </summary>
        internal static string ReminderSnoozeHint {
            get {
                return ResourceManager.GetString("ReminderSnoozeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die week ähnelt.
        /// </summary>
        internal static string ReminderWeek {
            get {
                return ResourceManager.GetString("ReminderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die weeks ähnelt.
        /// </summary>
        internal static string ReminderWeeks {
            get {
                return ResourceManager.GetString("ReminderWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please do not remove this key. ähnelt.
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show 24 hours... ähnelt.
        /// </summary>
        internal static string Show24Hours {
            get {
                return ResourceManager.GetString("Show24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string ShowAdvancedForm {
            get {
                return ResourceManager.GetString("ShowAdvancedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show business hours... ähnelt.
        /// </summary>
        internal static string ShowBusinessHours {
            get {
                return ResourceManager.GetString("ShowBusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die more... ähnelt.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
    }
}
