//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder-Klasse
    // mit einem Tool wie ResGen oder Visual Studio automatisch generiert.
    // Bearbeiten Sie zum Hinzufügen oder Entfernen eines Members die RESX-Datei, und führen Sie dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen das Visual Studio-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RadSpreadsheet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadSpreadsheet() {
        }
        
        /// <summary>
        ///   Gibt die von dieser Klasse verwendete zwischengespeicherte ResourceManager-Instanz zurück.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadSpreadsheet", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenlookups, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string ContextMenuCopy {
            get {
                return ResourceManager.GetString("ContextMenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        internal static string ContextMenuCut {
            get {
                return ResourceManager.GetString("ContextMenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string ContextMenuDeleteColumn {
            get {
                return ResourceManager.GetString("ContextMenuDeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string ContextMenuDeleteRow {
            get {
                return ResourceManager.GetString("ContextMenuDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide ähnelt.
        /// </summary>
        internal static string ContextMenuHideColumn {
            get {
                return ResourceManager.GetString("ContextMenuHideColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide ähnelt.
        /// </summary>
        internal static string ContextMenuHideRow {
            get {
                return ResourceManager.GetString("ContextMenuHideRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        internal static string ContextMenuPaste {
            get {
                return ResourceManager.GetString("ContextMenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string CustomFormatCancel {
            get {
                return ResourceManager.GetString("CustomFormatCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        internal static string CustomFormatCurrency {
            get {
                return ResourceManager.GetString("CustomFormatCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date and Time ähnelt.
        /// </summary>
        internal static string CustomFormatDateTime {
            get {
                return ResourceManager.GetString("CustomFormatDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number ähnelt.
        /// </summary>
        internal static string CustomFormatNumber {
            get {
                return ResourceManager.GetString("CustomFormatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string CustomFormatSave {
            get {
                return ResourceManager.GetString("CustomFormatSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string FilterMenuApply {
            get {
                return ResourceManager.GetString("FilterMenuApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        internal static string FilterMenuClear {
            get {
                return ResourceManager.GetString("FilterMenuClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Sorting ähnelt.
        /// </summary>
        internal static string FilterMenuClearSorting {
            get {
                return ResourceManager.GetString("FilterMenuClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date is ähnelt.
        /// </summary>
        internal static string FilterMenuDateIs {
            get {
                return ResourceManager.GetString("FilterMenuDateIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date is after ähnelt.
        /// </summary>
        internal static string FilterMenuDateIsAfter {
            get {
                return ResourceManager.GetString("FilterMenuDateIsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date is before ähnelt.
        /// </summary>
        internal static string FilterMenuDateIsBefore {
            get {
                return ResourceManager.GetString("FilterMenuDateIsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date is not ähnelt.
        /// </summary>
        internal static string FilterMenuDateIsNot {
            get {
                return ResourceManager.GetString("FilterMenuDateIsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter by condition ähnelt.
        /// </summary>
        internal static string FilterMenuFilterByCondition {
            get {
                return ResourceManager.GetString("FilterMenuFilterByCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter by value ähnelt.
        /// </summary>
        internal static string FilterMenuFilterByValue {
            get {
                return ResourceManager.GetString("FilterMenuFilterByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is equal to ähnelt.
        /// </summary>
        internal static string FilterMenuIsEqualTo {
            get {
                return ResourceManager.GetString("FilterMenuIsEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is greater than ähnelt.
        /// </summary>
        internal static string FilterMenuIsGreaterThan {
            get {
                return ResourceManager.GetString("FilterMenuIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is greater than or equal to  ähnelt.
        /// </summary>
        internal static string FilterMenuIsGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterMenuIsGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is less than ähnelt.
        /// </summary>
        internal static string FilterMenuIsLessThan {
            get {
                return ResourceManager.GetString("FilterMenuIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is less than or equal to  ähnelt.
        /// </summary>
        internal static string FilterMenuIsLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterMenuIsLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is not equal to  ähnelt.
        /// </summary>
        internal static string FilterMenuIsNotEqualTo {
            get {
                return ResourceManager.GetString("FilterMenuIsNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        internal static string FilterMenuNone {
            get {
                return ResourceManager.GetString("FilterMenuNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort Ascending ähnelt.
        /// </summary>
        internal static string FilterMenuSortAscending {
            get {
                return ResourceManager.GetString("FilterMenuSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort Descending ähnelt.
        /// </summary>
        internal static string FilterMenuSortDescending {
            get {
                return ResourceManager.GetString("FilterMenuSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text contains ähnelt.
        /// </summary>
        internal static string FilterMenuTextContains {
            get {
                return ResourceManager.GetString("FilterMenuTextContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text does not contain ähnelt.
        /// </summary>
        internal static string FilterMenuTextDoesNotContain {
            get {
                return ResourceManager.GetString("FilterMenuTextDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ends with ähnelt.
        /// </summary>
        internal static string FilterMenuTextEndsWith {
            get {
                return ResourceManager.GetString("FilterMenuTextEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text starts with ähnelt.
        /// </summary>
        internal static string FilterMenuTextStartsWith {
            get {
                return ResourceManager.GetString("FilterMenuTextStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string MessageDialogUseKeyboardOK {
            get {
                return ResourceManager.GetString("MessageDialogUseKeyboardOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die These actions cannot be invoked through the menu. Please use the keyboard shortcuts instead ähnelt.
        /// </summary>
        internal static string MessageDialogUseKeyboardText {
            get {
                return ResourceManager.GetString("MessageDialogUseKeyboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copying and pasting ähnelt.
        /// </summary>
        internal static string MessageDialogUseKeyboardTitle {
            get {
                return ResourceManager.GetString("MessageDialogUseKeyboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add column left ähnelt.
        /// </summary>
        internal static string ToolBarAddColumnLeft {
            get {
                return ResourceManager.GetString("ToolBarAddColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add column right ähnelt.
        /// </summary>
        internal static string ToolBarAddColumnRight {
            get {
                return ResourceManager.GetString("ToolBarAddColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add row above ähnelt.
        /// </summary>
        internal static string ToolBarAddRowAbove {
            get {
                return ResourceManager.GetString("ToolBarAddRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add row below ähnelt.
        /// </summary>
        internal static string ToolBarAddRowBelow {
            get {
                return ResourceManager.GetString("ToolBarAddRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Bottom ähnelt.
        /// </summary>
        internal static string ToolBarAlignBottom {
            get {
                return ResourceManager.GetString("ToolBarAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Center ähnelt.
        /// </summary>
        internal static string ToolBarAlignCenter {
            get {
                return ResourceManager.GetString("ToolBarAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Justify ähnelt.
        /// </summary>
        internal static string ToolBarAlignJustify {
            get {
                return ResourceManager.GetString("ToolBarAlignJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Left ähnelt.
        /// </summary>
        internal static string ToolBarAlignLeft {
            get {
                return ResourceManager.GetString("ToolBarAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Middle ähnelt.
        /// </summary>
        internal static string ToolBarAlignMiddle {
            get {
                return ResourceManager.GetString("ToolBarAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Right ähnelt.
        /// </summary>
        internal static string ToolBarAlignRight {
            get {
                return ResourceManager.GetString("ToolBarAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Align Top ähnelt.
        /// </summary>
        internal static string ToolBarAlignTop {
            get {
                return ResourceManager.GetString("ToolBarAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background Color ähnelt.
        /// </summary>
        internal static string ToolBarBackgroundColor {
            get {
                return ResourceManager.GetString("ToolBarBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bold ähnelt.
        /// </summary>
        internal static string ToolBarBold {
            get {
                return ResourceManager.GetString("ToolBarBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Border Color ähnelt.
        /// </summary>
        internal static string ToolBarBorderColor {
            get {
                return ResourceManager.GetString("ToolBarBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All borders ähnelt.
        /// </summary>
        internal static string ToolBarBordersAll {
            get {
                return ResourceManager.GetString("ToolBarBordersAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom border ähnelt.
        /// </summary>
        internal static string ToolBarBordersBottom {
            get {
                return ResourceManager.GetString("ToolBarBordersBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inside borders ähnelt.
        /// </summary>
        internal static string ToolBarBordersInside {
            get {
                return ResourceManager.GetString("ToolBarBordersInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inside horizontal borders ähnelt.
        /// </summary>
        internal static string ToolBarBordersInsideHorizontal {
            get {
                return ResourceManager.GetString("ToolBarBordersInsideHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inside vertical borders ähnelt.
        /// </summary>
        internal static string ToolBarBordersInsideVertical {
            get {
                return ResourceManager.GetString("ToolBarBordersInsideVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left border ähnelt.
        /// </summary>
        internal static string ToolBarBordersLeft {
            get {
                return ResourceManager.GetString("ToolBarBordersLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No border ähnelt.
        /// </summary>
        internal static string ToolBarBordersNo {
            get {
                return ResourceManager.GetString("ToolBarBordersNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outside borders ähnelt.
        /// </summary>
        internal static string ToolBarBordersOutside {
            get {
                return ResourceManager.GetString("ToolBarBordersOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right border ähnelt.
        /// </summary>
        internal static string ToolBarBordersRight {
            get {
                return ResourceManager.GetString("ToolBarBordersRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top border ähnelt.
        /// </summary>
        internal static string ToolBarBordersTop {
            get {
                return ResourceManager.GetString("ToolBarBordersTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string ToolBarCopy {
            get {
                return ResourceManager.GetString("ToolBarCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cut ähnelt.
        /// </summary>
        internal static string ToolBarCut {
            get {
                return ResourceManager.GetString("ToolBarCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        internal static string ToolBarData {
            get {
                return ResourceManager.GetString("ToolBarData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete cells ähnelt.
        /// </summary>
        internal static string ToolBarDeleteCells {
            get {
                return ResourceManager.GetString("ToolBarDeleteCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete column ähnelt.
        /// </summary>
        internal static string ToolBarDeleteColumn {
            get {
                return ResourceManager.GetString("ToolBarDeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete row ähnelt.
        /// </summary>
        internal static string ToolBarDeleteRow {
            get {
                return ResourceManager.GetString("ToolBarDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        internal static string ToolBarFilter {
            get {
                return ResourceManager.GetString("ToolBarFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font Family ähnelt.
        /// </summary>
        internal static string ToolBarFontFamily {
            get {
                return ResourceManager.GetString("ToolBarFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font Size ähnelt.
        /// </summary>
        internal static string ToolBarFontSize {
            get {
                return ResourceManager.GetString("ToolBarFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format ähnelt.
        /// </summary>
        internal static string ToolBarFormat {
            get {
                return ResourceManager.GetString("ToolBarFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic ähnelt.
        /// </summary>
        internal static string ToolBarFormatAutomatic {
            get {
                return ResourceManager.GetString("ToolBarFormatAutomatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currency ähnelt.
        /// </summary>
        internal static string ToolBarFormatCurrency {
            get {
                return ResourceManager.GetString("ToolBarFormatCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string ToolBarFormatDate {
            get {
                return ResourceManager.GetString("ToolBarFormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date time ähnelt.
        /// </summary>
        internal static string ToolBarFormatDateTime {
            get {
                return ResourceManager.GetString("ToolBarFormatDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Decrease decimal ähnelt.
        /// </summary>
        internal static string ToolBarFormatDecreaseDecimal {
            get {
                return ResourceManager.GetString("ToolBarFormatDecreaseDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duration ähnelt.
        /// </summary>
        internal static string ToolBarFormatDuration {
            get {
                return ResourceManager.GetString("ToolBarFormatDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Financial ähnelt.
        /// </summary>
        internal static string ToolBarFormatFinancial {
            get {
                return ResourceManager.GetString("ToolBarFormatFinancial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Increase decimal ähnelt.
        /// </summary>
        internal static string ToolBarFormatIncreaseDecimal {
            get {
                return ResourceManager.GetString("ToolBarFormatIncreaseDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number ähnelt.
        /// </summary>
        internal static string ToolBarFormatNumber {
            get {
                return ResourceManager.GetString("ToolBarFormatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Percent ähnelt.
        /// </summary>
        internal static string ToolBarFormatPercent {
            get {
                return ResourceManager.GetString("ToolBarFormatPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string ToolBarFormatTime {
            get {
                return ResourceManager.GetString("ToolBarFormatTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freeze columns ähnelt.
        /// </summary>
        internal static string ToolBarFreezeColumns {
            get {
                return ResourceManager.GetString("ToolBarFreezeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freeze panes ähnelt.
        /// </summary>
        internal static string ToolBarFreezePanes {
            get {
                return ResourceManager.GetString("ToolBarFreezePanes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Freeze rows ähnelt.
        /// </summary>
        internal static string ToolBarFreezeRows {
            get {
                return ResourceManager.GetString("ToolBarFreezeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        internal static string ToolBarHome {
            get {
                return ResourceManager.GetString("ToolBarHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horizontal alignment ähnelt.
        /// </summary>
        internal static string ToolBarHorizontalAlignment {
            get {
                return ResourceManager.GetString("ToolBarHorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert ähnelt.
        /// </summary>
        internal static string ToolBarInsert {
            get {
                return ResourceManager.GetString("ToolBarInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Insert cells ähnelt.
        /// </summary>
        internal static string ToolBarInsertCells {
            get {
                return ResourceManager.GetString("ToolBarInsertCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Italic ähnelt.
        /// </summary>
        internal static string ToolBarItalic {
            get {
                return ResourceManager.GetString("ToolBarItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge Cells ähnelt.
        /// </summary>
        internal static string ToolBarMergeCells {
            get {
                return ResourceManager.GetString("ToolBarMergeCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge Horizontally ähnelt.
        /// </summary>
        internal static string ToolBarMergeHorizontally {
            get {
                return ResourceManager.GetString("ToolBarMergeHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merge Vertically ähnelt.
        /// </summary>
        internal static string ToolBarMergeVertically {
            get {
                return ResourceManager.GetString("ToolBarMergeVertically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More formats... ähnelt.
        /// </summary>
        internal static string ToolBarMoreFormats {
            get {
                return ResourceManager.GetString("ToolBarMoreFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste ähnelt.
        /// </summary>
        internal static string ToolBarPaste {
            get {
                return ResourceManager.GetString("ToolBarPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redo ähnelt.
        /// </summary>
        internal static string ToolBarRedo {
            get {
                return ResourceManager.GetString("ToolBarRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string ToolBarSave {
            get {
                return ResourceManager.GetString("ToolBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort ähnelt.
        /// </summary>
        internal static string ToolBarSort {
            get {
                return ResourceManager.GetString("ToolBarSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort range A to Z ähnelt.
        /// </summary>
        internal static string ToolBarSortAscending {
            get {
                return ResourceManager.GetString("ToolBarSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sort range Z to A ähnelt.
        /// </summary>
        internal static string ToolBarSortDescending {
            get {
                return ResourceManager.GetString("ToolBarSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Color ähnelt.
        /// </summary>
        internal static string ToolBarTextColor {
            get {
                return ResourceManager.GetString("ToolBarTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wrap text ähnelt.
        /// </summary>
        internal static string ToolBarTextWrap {
            get {
                return ResourceManager.GetString("ToolBarTextWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Underline ähnelt.
        /// </summary>
        internal static string ToolBarUnderline {
            get {
                return ResourceManager.GetString("ToolBarUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Undo ähnelt.
        /// </summary>
        internal static string ToolBarUndo {
            get {
                return ResourceManager.GetString("ToolBarUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfreeze panes ähnelt.
        /// </summary>
        internal static string ToolBarUnfreeze {
            get {
                return ResourceManager.GetString("ToolBarUnfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unmerge ähnelt.
        /// </summary>
        internal static string ToolBarUnmerge {
            get {
                return ResourceManager.GetString("ToolBarUnmerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Validation ähnelt.
        /// </summary>
        internal static string ToolBarValidation {
            get {
                return ResourceManager.GetString("ToolBarValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vertical alignment ähnelt.
        /// </summary>
        internal static string ToolBarVerticalAlignment {
            get {
                return ResourceManager.GetString("ToolBarVerticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AnyValue ähnelt.
        /// </summary>
        internal static string ValidationAny {
            get {
                return ResourceManager.GetString("ValidationAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die between ähnelt.
        /// </summary>
        internal static string ValidationBetween {
            get {
                return ResourceManager.GetString("ValidationBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string ValidationCancel {
            get {
                return ResourceManager.GetString("ValidationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Criteria ähnelt.
        /// </summary>
        internal static string ValidationCriteria {
            get {
                return ResourceManager.GetString("ValidationCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Formula ähnelt.
        /// </summary>
        internal static string ValidationCustomFormula {
            get {
                return ResourceManager.GetString("ValidationCustomFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value is required ähnelt.
        /// </summary>
        internal static string ValidationCustomValueRequired {
            get {
                return ResourceManager.GetString("ValidationCustomValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        internal static string ValidationData {
            get {
                return ResourceManager.GetString("ValidationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        internal static string ValidationDate {
            get {
                return ResourceManager.GetString("ValidationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max date is required ähnelt.
        /// </summary>
        internal static string ValidationDateMaxRequired {
            get {
                return ResourceManager.GetString("ValidationDateMaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min date is required ähnelt.
        /// </summary>
        internal static string ValidationDateMinRequired {
            get {
                return ResourceManager.GetString("ValidationDateMinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die equal to ähnelt.
        /// </summary>
        internal static string ValidationEqualTo {
            get {
                return ResourceManager.GetString("ValidationEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die greater than ähnelt.
        /// </summary>
        internal static string ValidationGreaterThan {
            get {
                return ResourceManager.GetString("ValidationGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die greater than or equal to ähnelt.
        /// </summary>
        internal static string ValidationGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValidationGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a value that satisfies the formula: ähnelt.
        /// </summary>
        internal static string ValidationHintEmptyMessage {
            get {
                return ResourceManager.GetString("ValidationHintEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hint Message ähnelt.
        /// </summary>
        internal static string ValidationHintMessage {
            get {
                return ResourceManager.GetString("ValidationHintMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore Blank ähnelt.
        /// </summary>
        internal static string ValidationIgnoreBlank {
            get {
                return ResourceManager.GetString("ValidationIgnoreBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die less than ähnelt.
        /// </summary>
        internal static string ValidationLessThan {
            get {
                return ResourceManager.GetString("ValidationLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die less than or equal to ähnelt.
        /// </summary>
        internal static string ValidationLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValidationLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max ähnelt.
        /// </summary>
        internal static string ValidationMax {
            get {
                return ResourceManager.GetString("ValidationMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min ähnelt.
        /// </summary>
        internal static string ValidationMin {
            get {
                return ResourceManager.GetString("ValidationMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not between ähnelt.
        /// </summary>
        internal static string ValidationNotBetween {
            get {
                return ResourceManager.GetString("ValidationNotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not equal to ähnelt.
        /// </summary>
        internal static string ValidationNotEqualTo {
            get {
                return ResourceManager.GetString("ValidationNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number ähnelt.
        /// </summary>
        internal static string ValidationNumber {
            get {
                return ResourceManager.GetString("ValidationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max number is required ähnelt.
        /// </summary>
        internal static string ValidationNumberMaxRequired {
            get {
                return ResourceManager.GetString("ValidationNumberMaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min number is required ähnelt.
        /// </summary>
        internal static string ValidationNumberMinRequired {
            get {
                return ResourceManager.GetString("ValidationNumberMinRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On invalid data ähnelt.
        /// </summary>
        internal static string ValidationOnInvalidData {
            get {
                return ResourceManager.GetString("ValidationOnInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reject input ähnelt.
        /// </summary>
        internal static string ValidationReject {
            get {
                return ResourceManager.GetString("ValidationReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove validation ähnelt.
        /// </summary>
        internal static string ValidationRemove {
            get {
                return ResourceManager.GetString("ValidationRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string ValidationSave {
            get {
                return ResourceManager.GetString("ValidationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        internal static string ValidationText {
            get {
                return ResourceManager.GetString("ValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value is required ähnelt.
        /// </summary>
        internal static string ValidationTextValueRequired {
            get {
                return ResourceManager.GetString("ValidationTextValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        internal static string ValidationValue {
            get {
                return ResourceManager.GetString("ValidationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show warning ähnelt.
        /// </summary>
        internal static string ValidationWarning {
            get {
                return ResourceManager.GetString("ValidationWarning", resourceCulture);
            }
        }
    }
}
